### ISSUE TITLE
error installer not working

### ISSUE THREAD

**Issue by dannybreal** [bitcoal/bitcoalwallet#1]
![err](https://user-images.githubusercontent.com/17859995/33243126-b2e18096-d2e8-11e7-8848-011a334a1032.jpg)

**Comment by bitcoal** [comment]
Hello, this is because the release was compiled with Windows 8+ target.  I have recompiled it with Windows 7 support and have updated the release download.  Please download it again.

**Comment by dannybreal** [comment]
thank you sir :)
