### ISSUE TITLE
Wallet splash screen obscures alerts. Unable to select alert options. 

### ISSUE THREAD

**Issue by RandyMcMillan** [bitcoal/bitcoalwallet#10]
There is an alert under the splash screen that I can't select. Therefore I cant start the wallet.  

![screen shot 2018-05-21 at 3 23 07 pm 2](https://user-images.githubusercontent.com/152159/40325800-09cc4ec0-5d0b-11e8-9be3-d033accd9a20.png)

**Comment by RandyMcMillan** [comment]
![screen shot 2018-05-21 at 3 28 28 pm](https://user-images.githubusercontent.com/152159/40325989-bb87ed4a-5d0b-11e8-917c-a59ecf802325.png)

**Comment by onecoal** [comment]
Click on minimise to tray when this spalsh screen loads. And wait.

**Comment by RandyMcMillan** [comment]
I am unable to select it. Maybe in the source code you can make it selected by default. So by pressing RETURN it will automatically minimize.

**Comment by RandyMcMillan** [comment]
Or adding a keyboard short cut to minimize.

**Comment by ReCoal** [comment]
Close everything now. And open the wallet again. As soon as the splash screen is seen, click on minimise.. it will work.
